server:
  port: 8080

spring:
  profiles.active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 5
    min-idle: 1
    initial-size: 3
    validation-query: select 1
    test-on-borrow: true


  thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      content-type: text/html
      mode: HTML5

#设置静态资源访问路径
  resources:
    static-locations: classpath:/static/,classpath:/templates/


