CREATE TABLE IF NOT EXISTS `warning_strategy`(
`id` INT UNSIGNED AUTO_INCREMENT COMMENT 'INDEX ID',
`strategy_name` VARCHAR(100) UNIQUE NOT NULL COMMENT '策略名称',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`business` VARCHAR(100) NOT NULL COMMENT '业务名称',
`dimensions` TEXT NOT NULL COMMENT '维度条件',
`metrics` TEXT NOT NULL COMMENT '指标监控策略',
`contact_person` VARCHAR(100) NOT NULL COMMENT '报警人',
`status` VARCHAR(10) NOT NULL COMMENT '报警开关',
PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;