select domain,
	protocal,
	dst_ip,
	error_code,
	iplocations["country"] AS country,
	iplocations["province"] AS province,
	iplocations["isp"] AS isp,
	business,
	cdn,
	sum(download_time) download_time,
	count(1) total_num1,
	count(1) total_num2
from(select domain,
		protocal,
		dst_ip,
		error_code,
		if(issuccess = "true","dip-cdn-client-picture-aggregation-normal","dip-cdn-client-picture-aggregation-abnormal") business,
		ipToLocation(ip) AS iplocations,
		cdn,
		cast(download_time as float)
	from cdn_client_pic) a0
group by domain,
	protocal,
	dst_ip,
	error_code,
	iplocations["country"],
	iplocations["province"],
	iplocations["isp"],
	business,
	cdn