select business,
    domain,
	iplocations["country"] AS country,
	iplocations["province"] AS province,
	iplocations["isp"] AS isp,
	cdn,
	protocal,
	video_trace_dns_ip,
	video_firstframe_status,
	video_quit_status,
	error_code,
	sum(if(video_firstframe_status="success" and video_firstframe_time<=1000,1,0)) psr1_numerator,
	sum(if(video_firstframe_status="cancel" and video_firstframe_time<=1000,0,1)) psr1_denominator,
	sum(if(video_firstframe_status="success",1,0)) - sum(if(video_firstframe_status="cancel" and video_quit_status = "cancel",1,0)) succ_numerator,
	sum(if(video_firstframe_status = "" or video_firstframe_status = "cancel",0,1 )) succ_denominator,
	sum(video_firstframe_time) video_firstframe_time,
	count(1) total_num1,
	count(1) total_num2,
	sum(if(video_firstframe_status="cancel",1,0)) ff_cancel_num,
	sum(if(video_firstframe_status="error",1,0)) ff_error_num
from(select "dip-cdn-client-video-aggregation" business,
        domain,
		protocal,
		ipToLocation(ip) AS iplocations,
		video_firstframe_status,
		video_quit_status,
		cast(video_firstframe_time as float),
		video_trace_dns_ip,
		cdn,
		error_code
	from cdn_client_video) a0
group by business,
    domain,
	iplocations["country"],
	iplocations["province"],
	iplocations["isp"],
	cdn,
	protocal,
	video_trace_dns_ip,
	video_firstframe_status,
	video_quit_status,
    error_code